"""empty message

Revision ID: 8f2c7156b445
Revises: c236493f7827
Create Date: 2018-04-05 18:12:47.773931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2c7156b445'
down_revision = 'c236493f7827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'content')
    # ### end Alembic commands ###
