"""empty message

Revision ID: aa2d0841727e
Revises: 290f2eb9d15d
Create Date: 2018-04-01 11:31:21.975093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa2d0841727e'
down_revision = '290f2eb9d15d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('image1', sa.BLOB(), nullable=False))
    op.add_column('production', sa.Column('image2', sa.BLOB(), nullable=True))
    op.add_column('production', sa.Column('image3', sa.BLOB(), nullable=True))
    op.add_column('production', sa.Column('image4', sa.BLOB(), nullable=True))
    op.add_column('production', sa.Column('image5', sa.BLOB(), nullable=True))
    op.drop_column('production', 'province')
    op.drop_column('production', 'insertPic_4')
    op.drop_column('production', 'insertPic_3')
    op.drop_column('production', 'insertPic_2')
    op.drop_column('production', 'insertPic_1')
    op.drop_column('production', 'insertPic_0')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('insertPic_0', sa.BLOB(), nullable=False))
    op.add_column('production', sa.Column('insertPic_1', sa.BLOB(), nullable=True))
    op.add_column('production', sa.Column('insertPic_2', sa.BLOB(), nullable=True))
    op.add_column('production', sa.Column('insertPic_3', sa.BLOB(), nullable=True))
    op.add_column('production', sa.Column('insertPic_4', sa.BLOB(), nullable=True))
    op.add_column('production', sa.Column('province', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('production', 'image5')
    op.drop_column('production', 'image4')
    op.drop_column('production', 'image3')
    op.drop_column('production', 'image2')
    op.drop_column('production', 'image1')
    # ### end Alembic commands ###
