"""empty message

Revision ID: c236493f7827
Revises: dbcac9cee9f0
Create Date: 2018-04-01 15:15:09.485885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c236493f7827'
down_revision = 'dbcac9cee9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production', 'commitNum',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('production', 'viewNum',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production', 'viewNum',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('production', 'commitNum',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
