"""empty message

Revision ID: c887913af678
Revises: 349fafb462f7
Create Date: 2018-04-06 09:24:42.450952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c887913af678'
down_revision = '349fafb462f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production', 'image1',
               existing_type=sa.BLOB(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production', 'image1',
               existing_type=sa.BLOB(),
               nullable=True)
    # ### end Alembic commands ###
