"""empty message

Revision ID: dbcac9cee9f0
Revises: aa2d0841727e
Create Date: 2018-04-01 11:32:58.771809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbcac9cee9f0'
down_revision = 'aa2d0841727e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('province', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production', 'province')
    # ### end Alembic commands ###
